# Generated by Django 5.0.6 on 2024-06-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'admin'), ('seller', 'seller')], default='admin', max_length=10),
        ),
    ]
