# Generated by Django 5.0.6 on 2024-06-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'admin'), ('seller', 'seller'), ('client', 'client')], default='client', max_length=10),
        ),
    ]
