# Generated by Django 5.0.6 on 2024-06-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
